import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "@/lib/ApolloWrapper";
import { cn } from "@/lib/utils";
import MainHeader from "@/components/layout/main-header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "ForumUTE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <MainHeader />
        <ApolloWrapper>
          <div className="grid grid-cols-7 h-screen pt-[72px]">
            <div className="col-span-1"></div>
            <div className="col-span-5">{children}</div>
            <div className="col-span-1"></div>
          </div>
        </ApolloWrapper>
      </body>
    </html>
  );
}
