import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen items-center justify-center">
      <Image
        src={`/loginpage.jpg`}
        alt={"login image"}
        fill
        style={{ zIndex: "-1" }}
      />
      {children}
    </div>
  );
}
